### ISSUE TITLE
Can not remove icon

### ISSUE THREAD

**Issue by tomasSimandl** [ReliSA/IMiGEr#1]
Can not remove icon of related node.

Steps to reproduce:
1) Load diagram data/SPADe JSONs/aswi2017turbocore.json
2) Exclude node Retrospektiva
3) Show icon in related nodes in graph => icons are displayed
4) Remove icon in related ... => icons are not removed

Repeated clicking only appending more icons:
![image](https://user-images.githubusercontent.com/16165127/47988100-952fc780-e0e1-11e8-8be4-491d614a52fb.png)

**Comment by fidransky** [comment]
Fixed as part of frontend refactoring.
