### ISSUE TITLE
make it possible to save diagrams

### ISSUE THREAD

**Issue by pbrada** [ReliSA/IMiGEr#20]
It would be lovely ;-) to be able to save the diagram to a local file, and upload it at other time.

Could serve as a form of diagram backups.

**Comment by tomasSimandl** [comment]
Possibility to download JSON should be also on a graph page. Where will be downloaded actual diagram with all changes.

**Comment by fidransky** [comment]
True.

**Comment by fidransky** [comment]
Done but we need to redesign the graph screen heavily.
