### ISSUE TITLE
extend DB column for saving diagram JSON

### ISSUE THREAD

**Issue by fidransky** [ReliSA/IMiGEr#23]
At the moment, `diagram.graph_json` DB column uses datatype `text` which is limited to 64 KB which is not enough sometimes. Use `longtext` instead. Or even better, use `json` (available as of MySQL 5.7.8, [docs here](https://dev.mysql.com/doc/refman/5.7/en/json.html)).

**Comment by tomasSimandl** [comment]
I know about this problem. On [relisa-dev](http://relisa-dev.kiv.zcu.cz:8085/imiger) is datatype already changed to longtext, but JS error occures (see the attachment). Probably there is problem with timeout in ajax.  

![image](https://user-images.githubusercontent.com/16165127/52521262-b8d05400-2c74-11e9-9bca-1e1905acea41.png)

**Comment by fidransky** [comment]
Damn. I will start a new ticket for that.
